export const GET_PASSWORDS_PENDING = 'GET_PASSWORDS_PENDING';
export const GET_PASSWORDS_SUCCESS = 'GET_PASSWORDS_SUCCESS';
export const GET_PASSWORDS_FAILURE = 'GET_PASSWORDS_FAILURE';
export const GET_REMOVE_PASSWORDS_ITEMS = 'GET_REMOVE_PASSWORDS_ITEMS';

export const ADD_PASSWORD_PENDING = 'ADD_PASSWORD_PENDING';
export const ADD_PASSWORD_FAILURE = 'ADD_PASSWORD_FAILURE';

export const CHANGE_PASSWORD_PENDING = 'CHANGE_PASSWORD_PENDING';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const DELETE_PASSWORD_PENDING = 'DELETE_PASSWORD_PENDING';
export const DELETE_PASSWORD_SUCCESS = 'DELETE_PASSWORD_SUCCESS';
export const DELETE_PASSWORD_FAILURE = 'DELETE_PASSWORD_FAILURE';

export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const GET_USERS_FOR_SHARING_PENDING = 'GET_USERS_FOR_SHARING_PENDING';
export const GET_USERS_FOR_SHARING_SUCCESS = 'GET_USERS_FOR_SHARING_SUCCESS';
export const GET_USERS_FOR_SHARING_FAILURE = 'GET_USERS_FOR_SHARING_FAILURE';

export const SHARE_PASSWORDS_PENDING = 'SHARE_PASSWORDS_PENDING';
export const SHARE_PASSWORDS_SUCCESS = 'SHARE_PASSWORDS_SUCCESS';
export const SHARE_PASSWORDS_FAILURE = 'SHARE_PASSWORDS_FAILURE';

export const ACCEPT_PASSWORDS_PENDING = 'ACCEPT_PASSWORDS_PENDING';
export const ACCEPT_PASSWORDS_SUCCESS = 'ACCEPT_PASSWORDS_SUCCESS';
export const ACCEPT_PASSWORDS_FAILURE = 'ACCEPT_PASSWORDS_FAILURE';

export const DECLINE_PASSWORDS_PENDING = 'DECLINE_PASSWORDS_PENDING';
export const DECLINE_PASSWORDS_SUCCESS = 'DECLINE_PASSWORDS_SUCCESS';
export const DECLINE_PASSWORDS_FAILURE = 'DECLINE_PASSWORDS_FAILURE';
export const UPLOAD_PASSWORDS_PENDING = 'UPLOAD_PASSWORDS_PENDING';
export const UPLOAD_PASSWORDS_FAILURE = 'UPLOAD_PASSWORDS_FAILURE';
